<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.1" />
    <PackageReference Include="System.Text.Json" Version="9.0.5" />
    <PackageReference Include="Stub.System.Data.SQLite.Core.NetFramework" Version="1.0.119.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RCDragManagerProd\RCDragManagerProd.csproj" />
  </ItemGroup>

  <Target Name="CopySqliteInteropForTestHost" AfterTargets="Build">
    <Copy
      SourceFiles="$(TargetDir)x64\SQLite.Interop.dll"
      DestinationFiles="$(TargetDir)SQLite.Interop.dll"
      Condition="Exists('$(TargetDir)x64\\SQLite.Interop.dll')" />
  </Target>

</Project>
