using System;
using System.IO;
using RCDragManager.CodeStats.Models;

namespace RCDragManager.CodeStats.Modules
{
    public static class MarkdownExporter
    {
        public static void Export(ProjectMap map, string root)
        {
            Console.WriteLine("[OUT] Markdown Exporter");

            string dir = Path.Combine(root, "ProjectAnalysis");
            Directory.CreateDirectory(dir);

            string path = Path.Combine(dir, "ProjectMap.md");

            string content = "# Project Map (stub)\n\nGenerated by RCDragManager.CodeStats.\n";
            File.WriteAllText(path, content);
        }
    }
}
