using System;
using System.IO;
using System.Linq;
using System.Text;
using RCDragManager.CodeStats.Models;

namespace RCDragManager.CodeStats.Modules
{
    public static class MarkdownExporter
    {
        public static void Export(ProjectMap map, string root)
        {
            Console.WriteLine("[OUT] Markdown Exporter");

            string dir = Path.Combine(root, "ProjectAnalysis");
            Directory.CreateDirectory(dir);

            string path = Path.Combine(dir, "ProjectMap.md");

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("# RC Drag Manager – CodeStats Project Map");
            sb.AppendLine();
            sb.AppendLine("Generated by RCDragManager.CodeStats.");
            sb.AppendLine();

            sb.AppendLine("## Summary");
            sb.AppendLine();
            sb.AppendLine("- Classes      : " + map.Classes.Count);
            sb.AppendLine("- Methods      : " + map.Methods.Count);
            sb.AppendLine("- Events       : " + map.Events.Count);
            sb.AppendLine("- UI Controls  : " + map.UIControls.Count);
            sb.AppendLine("- Repositories : " + map.Repositories.Count);
            sb.AppendLine("- Dependencies : " + map.Dependencies.Count);
            sb.AppendLine("- Cycles       : " + map.Cycles.Count);
            sb.AppendLine();

            int asyncCount = map.Methods.Count(m => m.IsAsync);
            sb.AppendLine("Async methods: " + asyncCount);
            sb.AppendLine();

            sb.AppendLine("## Top Classes by Method Count (max 10)");
            sb.AppendLine();

            var methodsByClass = map.Methods
                .Where(m => !string.IsNullOrWhiteSpace(m.DeclaringFullName))
                .GroupBy(m => m.DeclaringFullName!)
                .Select(g => new
                {
                    Name = g.Key,
                    Count = g.Count()
                })
                .OrderByDescending(x => x.Count)
                .Take(10)
                .ToList();

            if (methodsByClass.Count == 0)
            {
                sb.AppendLine("_No methods found._");
            }
            else
            {
                for (int i = 0; i < methodsByClass.Count; i++)
                {
                    sb.AppendLine("- " + methodsByClass[i].Name + " : " + methodsByClass[i].Count + " methods");
                }
            }

            sb.AppendLine();
            sb.AppendLine("## Repositories by SQL Usage (max 10)");
            sb.AppendLine();

            var repoBySql = map.Repositories
                .Select(r => new
                {
                    Name = r.FullName ?? r.Name,
                    Count = r.SqlUsages.Count
                })
                .OrderByDescending(x => x.Count)
                .Take(10)
                .ToList();

            if (repoBySql.Count == 0)
            {
                sb.AppendLine("_No repository SQL usage detected._");
            }
            else
            {
                for (int i = 0; i < repoBySql.Count; i++)
                {
                    sb.AppendLine("- " + repoBySql[i].Name + " : " + repoBySql[i].Count + " queries");
                }
            }

            sb.AppendLine();
            sb.AppendLine("## UI Controls per Form");
            sb.AppendLine();

            var controlsByForm = map.UIControls
                .GroupBy(c => c.DeclaringFullName ?? c.DeclaringType ?? "<Unknown>")
                .Select(g => new
                {
                    Form = g.Key,
                    Count = g.Count()
                })
                .OrderByDescending(x => x.Count)
                .ToList();

            for (int i = 0; i < controlsByForm.Count; i++)
            {
                sb.AppendLine("- " + controlsByForm[i].Form + " : " + controlsByForm[i].Count + " controls");
            }

            sb.AppendLine();
            sb.AppendLine("## Dependency / Cycle Stats");
            sb.AppendLine();

            sb.AppendLine("- Dependency edges: " + map.Dependencies.Count);
            sb.AppendLine("- Nodes with cycles: " + map.Cycles.Select(c => c.FromFullName).Distinct().Count());
            sb.AppendLine();

            sb.AppendLine("## Top-Level Types (first 20)");
            sb.AppendLine();

            int count = 0;
            for (int i = 0; i < map.Classes.Count && count < 20; i++)
            {
                ClassInfo c = map.Classes[i];
                string full = string.IsNullOrWhiteSpace(c.Namespace) ? c.Name : c.Namespace + "." + c.Name;

                sb.Append("- ");
                sb.Append(full);
                sb.Append("  (");
                sb.Append(c.FilePath);
                sb.AppendLine(")");

                count = count + 1;
            }

            File.WriteAllText(path, sb.ToString());
        }
    }
}
