[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function Get-MSBuildPath {
    $vsWhere = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
    if (Test-Path $vsWhere) {
        $path = & $vsWhere -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe | Select-Object -First 1
        if ($path) {
            return $path.Trim()
        }
    }

    $dotnet = Get-Command dotnet.exe -ErrorAction SilentlyContinue
    if ($dotnet) {
        return "dotnet msbuild"
    }

    throw "MSBuild was not found. Install Visual Studio Build Tools or Visual Studio with MSBuild."
}

function Get-ISCCPath {
    if ($env:INNOSETUP_ISCC -and (Test-Path $env:INNOSETUP_ISCC)) {
        return $env:INNOSETUP_ISCC
    }

    $command = Get-Command ISCC.exe -ErrorAction SilentlyContinue
    if ($command) {
        return $command.Source
    }

    $commonPaths = @(
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe",
        "C:\Program Files\Inno Setup 6\ISCC.exe"
    )

    foreach ($path in $commonPaths) {
        if (Test-Path $path) {
            return $path
        }
    }

    throw "ISCC.exe was not found. Install Inno Setup 6 or set INNOSETUP_ISCC to its full path."
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $scriptDir
$projectPath = Join-Path $repoRoot "src\RCDragManagerProd\RCDragManagerProd.csproj"
$releaseDir = Join-Path $repoRoot "src\RCDragManagerProd\bin\Release"
$payloadDir = Join-Path $scriptDir "Payload"
$outputDir = Join-Path $scriptDir "output"
$issPath = Join-Path $scriptDir "RCDragManager.iss"
$payloadReadme = Join-Path $payloadDir "README.txt"
$exePath = Join-Path $releaseDir "RCDragManagerProd.exe"

Write-Step "Locating build tools"
$msbuildPath = Get-MSBuildPath
$isccPath = Get-ISCCPath
Write-Host "MSBuild: $msbuildPath"
Write-Host "ISCC:    $isccPath"

Write-Step "Cleaning previous installer payload and output"
if (Test-Path $payloadDir) {
    Remove-Item $payloadDir -Recurse -Force
}
if (Test-Path $outputDir) {
    Remove-Item $outputDir -Recurse -Force
}
New-Item -ItemType Directory -Path $payloadDir | Out-Null
New-Item -ItemType Directory -Path $outputDir | Out-Null

Write-Step "Building Release output"
if ($msbuildPath -eq "dotnet msbuild") {
    & dotnet msbuild $projectPath /t:Clean,Build /p:Configuration=Release /p:Platform="AnyCPU" /nologo /verbosity:minimal
}
else {
    & $msbuildPath $projectPath /t:Clean,Build /p:Configuration=Release /p:Platform="AnyCPU" /nologo /verbosity:minimal
}

if (-not (Test-Path $exePath)) {
    throw "Build succeeded without producing $exePath"
}

$version = [System.Diagnostics.FileVersionInfo]::GetVersionInfo($exePath).FileVersion
if ([string]::IsNullOrWhiteSpace($version)) {
    throw "Could not read file version from $exePath"
}
Write-Host "Built version: $version"

Write-Step "Copying Release output into installer payload"
Copy-Item (Join-Path $releaseDir "*") -Destination $payloadDir -Recurse -Force

$junkPatterns = @("*.pdb", "*.xml")
foreach ($pattern in $junkPatterns) {
    Get-ChildItem $payloadDir -Recurse -File -Filter $pattern | Remove-Item -Force
}

@(
    "This folder is generated by Installer\build-installer.ps1.",
    "Source payload comes from src\RCDragManagerProd\bin\Release.",
    "Do not hand-edit these files; rerun the script instead."
) | Set-Content -Path $payloadReadme -Encoding ASCII

Write-Step "Compiling the Inno Setup installer"
& $isccPath "/DMyAppVersion=$version" $issPath

$installer = Get-ChildItem $outputDir -Filter "RC-Drag-Manager-Setup-*.exe" | Sort-Object LastWriteTime -Descending | Select-Object -First 1
if (-not $installer) {
    throw "Inno Setup finished without producing an installer in $outputDir"
}

Write-Step "Installer build complete"
Write-Host "Installer: $($installer.FullName)" -ForegroundColor Green
